---
#
#  HOSTS
#
#  * Note:
#  * - Single host lines can skip the missing colon ":"
#  * - Multiple host lines can't :(, so ensure they all end with a ":"
#
all:
  #  Global hosts
  hosts:
    localhost:
      ansible_connection: local
    rpi0:
      ansible_connection: ssh
      ansible_host: 192.168.136.30
      ansible_user: pi
    rpi1:
      ansible_connection: ssh
      ansible_host: 192.168.136.31
      ansible_user: pi
    rpi2:
      ansible_connection: ssh
      ansible_host: 192.168.136.32
      ansible_user: pi
    rpi3:
      ansible_connection: ssh
      ansible_host: 192.168.136.33
      ansible_user: pi
    rpi4:
      ansible_connection: ssh
      ansible_host: 192.168.136.34
      ansible_user: pi
  vars:
    router_ip: 192.168.136.1
    dhcp_ip: 192.168.136.1 8.8.8.8 8.8.4.4

  #  Host groups
  children:
    local:
      hosts:
        localhost:
    #  All boxes
    pis:
      hosts:
        rpi0:
        rpi1:
        rpi2:
        rpi3:
        rpi4:

    #  Only for "RPI 3 Model B" boxes
    k3s:
      hosts:
        rpi0:
        rpi1:
        rpi2:
        rpi3:

    k3s_master:
      hosts:
        rpi0:

    k3s_agent:
      hosts:
        rpi1:
        rpi2:
        rpi3:
