---
#
#  HOSTS
#
#  * Note:
#  * - Single host lines can skip the missing colon ":"
#  * - Multiple host lines can't :(, so ensure they all end with a ":"
#
all:
  #  Global hosts
  hosts:
    localhost:
      ansible_connection: local
    rpi0:
      ansible_connection: ssh
      ansible_host: 192.168.136.20
      ansible_user: pi
    rpi1:
      ansible_connection: ssh
      ansible_host: 192.168.136.21
      ansible_user: pi
    rpi2:
      ansible_connection: ssh
      ansible_host: 192.168.136.22
      ansible_user: pi
    rpi3:
      ansible_connection: ssh
      ansible_host: 192.168.136.23
      ansible_user: pi
    rpi4:
      ansible_connection: ssh
      ansible_host: 192.168.136.24
      ansible_user: pi
  vars:

  #  Host groups
  children:
    local:
      hosts:
        localhost:
    #  All boxes
    pis:
      hosts:
        rpi0:
        rpi1:
        rpi2:
        rpi3:
        rpi4:

    #  Only for "RPI 3 Model B" boxes
    k3s:
      hosts:
        rpi0:
        rpi1:
        rpi2:
        rpi3:

    k3s_master:
      hosts:
        rpi0:

    k3s_agent:
      hosts:
        rpi1:
        rpi2:
        rpi3:
