---
#
#  Update apt packages + distro (one at the time)
#
- name: Package install + refresh
  hosts: pis
  become: yes
  serial: 1
  vars_files:
  - ../vars/main.yml

  tasks:
  - name: Update apt caches
    apt:
      update_cache: yes
      cache_valid_time: "{{ apt_cache_time }}"

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Install default packages
    apt:
      pkg: "{{ apt_pkgs_to_install }}"
      state: present

#
#  Configure RPi hosts for the 1st time (in parallel)
#
- name: General machine configuration tasks
  hosts: pis
  become: yes
  vars_files:
  - ../vars/main.yml

  tasks:
  - name: Set new MOTD
    copy:
      dest: /etc/update-motd.d/10-motd
      content: "{{ motd }}"
      owner: root
      group: root
      mode: 0755

  - name: Remove old MOTD files
    file:
      name: "{{ item }}"
      state: absent
    loop:
    - /etc/update-motd.d/10-uname
    - /etc/motd

  - name: Set global aliases
    copy:
      dest: /etc/profile.d/10-aliases.sh
      content: |
        #
        #  Global aliases
        #
        {{ aliases }}
      owner: root
      group: root
      mode: 0755

  - name: Set global prompt
    copy:
      dest: /etc/profile.d/10-prompt.sh
      content: |
        #
        #  Global Bash Prompt
        #
        export PS1='\[\033[1;32m\]\u\[\033[0m\]@\[\033[1;30m\]\H\[\033[0m\]:\[\033[0;34m\]\w\[\033[0m\]\$ '
      owner: root
      group: root
      mode: 0755

  - name: Set timezone
    timezone:
      name: UTC
    register: timezone_update

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"
    register: hostname_update

  - name: Set hostname in /etc/hosts
    blockinfile:
      path: /etc/hosts
      insertbefore: EOF
      marker: "#-- {mark} ANSIBLE MANAGED --"
      content: |
        127.0.0.1 {{ inventory_hostname }}

  - name: Set global RPi configs
    blockinfile:
      path: /boot/config.txt
      insertbefore: EOF
      marker: "#-- {mark} ANSIBLE MANAGED --"
      content: |
        #  Set GPU memory to minimum possible
        gpu_mem = 16

        #  Disable WiFi
        dtoverlay = pi3-disable-wifi

        #  Disable Bluetooth
        dtoverlay = pi3-disable-bt
    register: boot_config

  - name: Remove packages off the cache
    apt:
      autoclean: yes

  - name: Remove dependencies no longer needed
    apt:
      autoremove: yes

  - name: Expand root filesystem
    command: /usr/bin/raspi-config --expand-rootfs

  - name: Disable swap
    shell: |
      dphys-swapfile swapoff
      dphys-swapfile uninstall
      systemctl disable dphys-swapfile

  - name: Set static IP
    blockinfile:
      path: /etc/dhcpcd.conf
      insertbefore: EOF
      marker: "#-- {mark} ANSIBLE MANAGED --"
      content: |
        interface eth0

        static ip_address={{ ansible_host }}/24
        static routers={{ router_ip }}
        static domain_name_servers={{ dhcp_ip }}
    register: static_ip

  - name: Reboot RPis if server changes occurred
    block:

    - name: Rebooting boxes
      reboot:
        reboot_timeout: 300

    - name: Waiting for boxes to come back
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

    when: timezone_update is changed or hostname_update is changed or static_ip is changed or boot_config is changed
