---
#
#  Configure RPi hosts
#
- name: 1st time host configuration
  hosts: pis
  become: yes
  vars_files:
  - ../vars/main.yml
  vars_prompt:
  - name: "ansible_password"
    prompt: "ssh password"
    private: yes

  tasks:
  - name: Ensure .ssh folder exist
    file:
      path: /home/pi/.ssh
      state: directory
      owner: pi
      group: pi
      mode: 0700

  - name: Add ansible ssh key
    authorized_key:
      user: pi
      key: "{{ ansible_ssh_key }}"
      exclusive: yes

  - name: Reset pi user password
    user:
      name: pi
      password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,punctuation') | password_hash('sha512') }}"

  - name: Disable empty password login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?PermitEmptyPasswords'
      line: "PermitEmptyPasswords no"

  - name: Disable remote root login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin'
      line: "PermitRootLogin no"

  - name: Disable password login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^(#\s*)?PasswordAuthentication '
      line: "PasswordAuthentication no"

  - name: Enable PAM
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?UsePAM'
      line: "UsePAM yes"

  - name: Reload SSH
    systemd:
      name: ssh
      state: reloaded
      enabled: yes
